### ISSUE TITLE
No implicit children in react 18 breaks typings

### ISSUE THREAD

**Issue by lordspace74** [LinusU/react-with-separator#5]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-with-separator@1.2.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-with-separator/index.d.ts b/node_modules/react-with-separator/index.d.ts
index d40d446..067c66e 100644
--- a/node_modules/react-with-separator/index.d.ts
+++ b/node_modules/react-with-separator/index.d.ts
@@ -9,6 +9,6 @@ declare interface Props {
   trailing?: boolean
 }
 
-declare const WithSeparator: FC<Props>
+declare const WithSeparator: FC<PropsWithChildren<Props>>
 
 export = WithSeparator
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by LinusU** [comment]
Thanks for reporting! This is now fixed in [🚢 1.2.1 / 2022-08-30](https://github.com/LinusU/react-with-separator/releases/tag/v1.2.1)
